
logging:
  level:
    org:
      springframework: DEBUG
    com:
      netflix: DEBUG
---
spring:
  profiles: cloud
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.discovery-service.credentials.url}
    