zuul:
  routes:
    frontend:
      path: /frontend/**
      serviceId: frontend-service
    identity:
      path: /identity/**
      serviceId: identity-service
    catalog:
      path: /catalog/**
      serviceId: catalogue-service-srdc
    business-process:
      path: /business-process/**
      serviceId: business-process-service

---

spring:
  profiles: dev

eureka:
    instance:
        registryFetchIntervalSeconds: 1
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 5
    client:
        initialInstanceInfoReplicationIntervalSeconds: 5
ribbon:
    ServerListRefreshInterval: 1000
