zuul:
  routes:
    frontend:
      path: /frontend/**
      serviceId: frontend-service
    identity:
      path: /identity/**
      serviceId: identity-service
    catalog:
      path: /catalog/**
      serviceId: catalogue-service-srdc
    business-process:
      path: /business-process/**
      serviceId: business-process-service

---

spring:
  profiles: dev

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 1

ribbon:
  ServerListRefreshInterval: 3
  ReadTimeout: 100000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false